### ISSUE TITLE
Needs stdcall support for win*

### ISSUE THREAD

**Issue by edwintorok** [dbuenzli/tgls#1]
For porting to windows support for stdcall is required in ctypes: https://github.com/ocamllabs/ocaml-ctypes/issues/121

**Comment by dbuenzli** [comment]
Not sure I understand what this is about. Do I need to do something special ?

**Comment by yallop** [comment]
I think passing [`~abi:Libffi_abi.stdcall`](https://github.com/yallop/ocaml-ctypes/blob/master/src/ctypes-foreign-base/libffi_abi.mli#L29) to [`foreign`](https://github.com/yallop/ocaml-ctypes/blob/d27141372bb355ec84674691aad4f3eda3f173d0/src/ctypes-foreign-unthreaded/foreign.mli#L11) should be sufficient.

**Comment by dbuenzli** [comment]
> I think passing ~abi:Libffi_abi.stdcall to foreign should be sufficient.

Thanks Jeremie. Only on windows I guess ?

**Comment by yallop** [comment]
Yes.  Explicitly passing `Libffi_abi.default_abi` on other platforms might make it easier to conditionalize.
