### ISSUE TITLE
tgls on FreeBSD

### ISSUE THREAD

**Issue by CodiePP** [dbuenzli/tgls#17]
I think it failed to dynamically link the libGL.so library on FreeBSD.

 > uname -s
 FreeBSD

 > ./linkgl3.native
 [FAIL] glProvokingVertex not found for OpenGL 3.2

the library can be found with:
> pkg-config --cflags --libs gl
-DMESA_EGL_NO_X11_HEADERS -I/usr/local/include/libdrm -D_THREAD_SAFE -I/usr/local/include -L/usr/local/lib -lGL  

Hope this helps. Thanks.

**Comment by dbuenzli** [comment]
Thanks for the info. Could please try the fix by doing a: 

```
opam pin add tgls https://github.com/dbuenzli/tgls.git
opam upgrade tgls
```

**Comment by dbuenzli** [comment]
Btw. @yallop any idea if `-Wl,-no-as-needed` is needed on FreeBSD ? I did not add the flag.

**Comment by CodiePP** [comment]
Passed!

> ./trigl3.native 
INFO: 
Renderer Mesa DRI Intel(R) Ivybridge Mobile 
         OpenGL 3.2 (Core Profile) Mesa 10.4.6 / GLSL 3.30

> ~/src/ml/t_tgls]$ ./linkgl3.native 
 [OK] Found glProvokingVertex for OpenGL 3.2

> ~/src/ml/t_tgls]$ ./linkgl4.native 
 [OK] Found glBindTransformFeedback for OpenGL 4.0

**Comment by yallop** [comment]
> Btw. @yallop any idea if `-Wl,-no-as-needed` is needed on FreeBSD ? I did not add the flag. 

It's not needed as far as I know (and the passing test appears to confirm that).

**Comment by dbuenzli** [comment]
Thanks Jeremie.
