### ISSUE TITLE
bind_buffer function type mistake?

### ISSUE THREAD

**Issue by linsyking** [dbuenzli/tgls#31]
From the official [documentation](https://docs.gl/gl3/glBindBuffer), the `glBindBuffer` has the following signature:

```
void glBindBuffer(GLenum target, GLuint buffer);
```

So I think the second argument should has type of `int32` rather than `int`.

**Comment by dbuenzli** [comment]
Is that an issue for you ?

**Comment by linsyking** [comment]
For example, when I want to bindbuffer after genbuffer:

```
Gl.gen_buffers 1 vbo;
Gl.bind_buffer Gl.array_buffer @@ Int32.to_int vbo.{0};
```

I need to convert int32 to int manually.

**Comment by dbuenzli** [comment]
Indeed the [sample code](https://github.com/dbuenzli/tgls/blob/eda88cff8d2197eb478b86c7deb39803981f4447/test/trigl3.ml#L23-L25) does that. I think the idea here was that you'd convert them directly after the `gen_buffer` so that you can store and use them unboxed in your data structures.
